compressionLevel: mixed

enableGlobalCache: false

# This enables inline builds for dependencies.
# It's valid if you want Yarn to handle builds directly during dependency installation.
enableInlineBuilds: false

enableScripts: false

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.5.2.cjs

# If true, Yarn will run your constraints right after finishing its installs.
# This may help decrease the feedback loop delay by catching errors long before your CI would even report them.
enableConstraintsChecks: false


# If true (the default on CI), Yarn will refuse to change the lockfile in any way,
# whether it would add new entries or remove them.
# Other files can be added to the checklist via the immutablePatterns setting.
#enableImmutableInstalls: true


logFilters:
  - code: YN0009
    level: info

